### ISSUE TITLE
watch example

### ISSUE THREAD

**Issue by justmisam** [sunriselink/TelegramApi#1]
Hi
Thanks for your great work.
How can I watch the example? `gulp watch` or any commands?

**Comment by sunriselink** [comment]
Hi.

You need to execute a command `npm run build` and open `example/index.html`.

This version was created is still in the initial development and used for debugging methods, so it is not a living example of the library.

(Google Translate).

**Comment by sunriselink** [comment]
Now you can excute command `npm install && npm start` (on release 1.2)

**Comment by justmisam** [comment]
Sounds great! Thank you very much.
