### ISSUE TITLE
navigator is not defined.

### ISSUE THREAD

**Issue by Haizanjs** [sunriselink/TelegramApi#14]
Discord Token: AAAAAAAAAAAA
D:\discordjs\telegram_automessage\node_modules\telegram-api-js\dist\telegramApi.js:58
function BigInteger(a,b,c){null!=a&&("number"==typeof a?this.fromNumber(a,b,c):null==b&&"string"!=typeof a?this.fromString(a,256):this.fromString(a,b))}function nbi(){return new BigInteger(null)}function am1(a,b,c,d,e,f){for(;--f>=0;){var g=b*this[a++]+c[d]+e;e=Math.floor(g/67108864),c[d++]=67108863&g}return e}function am2(a,b,c,d,e,f){for(var g=32767&b,h=b>>15;--f>=0;){var i=32767&this[a],j=this[a++]>>15,k=h*i+j*g;i=g*i+((32767&k)<<15)+c[d]+(1073741823&e),e=(i>>>30)+(k>>>15)+h*j+(e>>>30),c[d++]=1073741823&i}return e}function am3(a,b,c,d,e,f){for(var g=16383&b,h=b>>14;--f>=0;){var i=16383&this[a],j=this[a++]>>14,k=h*i+j*g;i=g*i+((16383&k)<<14)+c[d]+e,e=(i>>28)+(k>>14)+h*j,c[d++]=268435455&i}return e}function int2char(a){return BI_RM.charAt(a)}function intAt(a,b){var c=BI_RC[a.charCodeAt(b)];return null==c?-1:c}function bnpCopyTo(a){for(var b=this.t-1;b>=0;--b)a[b]=this[b];a.t=this.t,a.s=this.s}function bnpFromInt(a){this.t

ReferenceError: navigator is not defined
    at D:\discordjs\telegram_automessage\node_modules\telegram-api-js\dist\telegramApi.js:58:17304
    at Object.<anonymous> (D:\discordjs\telegram_automessage\node_modules\telegram-api-js\dist\telegramApi.js:5397:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\discordjs\telegram_automessage\index.js:10:21)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by yubi00** [comment]
i got the same error. Can anyone advice on how to fix this error?
